version: '3.5'

services:
  postgres:
    container_name: nifi_volume
    image: apache/nifi:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
       - D:\Docker\Volumes\Nifi/logs:/opt/nifi/nifi-current/logs
       - D:\Docker\Volumes\Nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
       - D:\Docker\Volumes\Nifi/state:/opt/nifi/nifi-current/state
       - D:\Docker\Volumes\Nifi/conf:/opt/nifi/nifi-current/conf
       - D:\Docker\Volumes\Nifi/content_repository:/opt/nifi/nifi-current/content_repository
       - D:\Docker\Volumes\Nifi/database_repository:/opt/nifi/nifi-current/database_repository
       - D:\Docker\Volumes\Nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
    ports:
      - "8080:8080"
    networks:
      - nifi_volume
    restart: unless-stopped
  
networks:
  nifi_volume:
    driver: bridge

volumes:
    postgres: