version: '3.4'

services:
  
  elasticsearch:
   container_name: elasticsearch
   image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
   restart: always
   ports:
    - 9200:9200
   volumes:
    - elasticsearch-data:/usr/share/elasticsearch/data
   environment:
    - xpack.monitoring.enabled=true
    - xpack.watcher.enabled=false
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    - ELASTICSEARCH_USERNAME=elastic
    - ELASTICSEARCH_PASSWORD=passw
   networks:
    - elastic

  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:7.8.0
   restart: always
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ELASTICSEARCH_URL=http://localhost:9200
    - ELASTICSEARCH_USERNAME=elastic
    - ELASTICSEARCH_PASSWORD=passw
   networks:
    - elastic
  sqlserver:
   container_name: sqlserver
   image: mcr.microsoft.com/mssql/server
   restart: always
   ports:
    - 1433:1433
   environment:
    - SA_PASSWORD=senha@019
    - ACCEPT_EULA=Y
   networks:
    - elastic
  
networks:
  elastic:
    driver: bridge

volumes:
  elasticsearch-data: